
jobs:
  include:
    - name: "Protocol documentation"
      addons:
        snaps:
          - hugo

      script:
          - cd ProtocolSpecification
          - rm -rf public  # Remove old build folder
          - hugo

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        verbose: true
        local-dir: ProtocolSpecification/public
        target_branch: gh-pages
        on:
          branch: master
